import tkinter as tk
import tkinter.ttk as ttk

class Application(tk.Tk):
    def __init__(self):
        super().__init__()
        self.geometry("800x325")
        self.title("RevasManager")
        self.frameconfig = ttk.LabelFrame(self, text="Konfiguruj", width=625, height=50)
        self.frameconfig.grid(row=0, column=0, padx=(10, 2), pady=10)
        self.roundframe = ttk.LabelFrame(self, text="Runda", width=140, height=95)
        self.roundframe.grid(row=0, column=1, padx=(5, 10))
        self.options = ttk.Notebook(self.frameconfig, width=625, height=50)
        self.oferty = ttk.Frame(self.options)
        self.pracownicy = ttk.Frame(self.options)
        self.oplaty = ttk.Frame(self.options)
        self.options.add(self.oferty, text="Oferty")
        self.options.add(self.pracownicy, text="Pracownicy")
        self.options.add(self.oplaty, text="Opłaty")
        self.options.pack(expand=1, fill='both')
        #Oferty
        self.nazwalabel = ttk.Label(self.oferty, text="Nazwa")
        self.nazwalabel.grid(row=0, column=0, padx=10)
        self.nazwa = ttk.Entry(self.oferty)
        self.nazwa.grid(row=1, column=0, padx=10, pady=5)
        self.poptylabel = ttk.Label(self.oferty, text="Popyt roczny")
        self.poptylabel.grid(row=0, column=1, padx=10)
        self.popyt = ttk.Entry(self.oferty, width=10)
        self.popyt.grid(row=1, column=1, padx=10, pady=5)
        self.cenalabel = ttk.Label(self.oferty, text="Cena za usługę")
        self.cenalabel.grid(row=0, column=2, padx=10)
        self.cena = ttk.Entry(self.oferty, width=10)
        self.cena.grid(row=1, column=2, padx=10, pady=5)
        self.godzinylabel = ttk.Label(self.oferty, text="Godziny")
        self.godzinylabel.grid(row=0, column=3, padx=10)
        self.godziny = ttk.Entry(self.oferty, width=10)
        self.godziny.grid(row=1, column=3, padx=10, pady=5)
        self.wspolczynniklabel = ttk.Label(self.oferty, text="Współczynniki")
        self.wspolczynniklabel.grid(row=0, column=4, padx=10)
        self.wspolczynnik = ttk.Button(self.oferty, text="Otwórz Menu")
        self.wspolczynnik.grid(row=1, column=4, padx=10, pady=5)
        self.dodajoferte = ttk.Button(self.oferty, text="Dodaj oferte")
        self.dodajoferte.grid(row=0, rowspan=2, column=5, padx=10, pady=10)
        #Pracownicy
        self.imielable = ttk.Label(self.pracownicy, text="Imie")
        self.imielable.grid(row=0, column=0, padx=15)
        self.imie = ttk.Entry(self.pracownicy)
        self.imie.grid(row=1, column=0, padx=15, pady=5)
        self.nazwiskolabel = ttk.Label(self.pracownicy, text="Nazwisko")
        self.nazwiskolabel.grid(row=0, column=1, padx=15)
        self.nazwisko = ttk.Entry(self.pracownicy)
        self.nazwisko.grid(row=1, column=1, padx=15, pady=5)
        self.wynagrodzenielabel = ttk.Label(self.pracownicy, text="Wynagrodzenie")
        self.wynagrodzenielabel.grid(row=0, column=2, padx=15)
        self.wynagrodzenie = ttk.Entry(self.pracownicy, width=15)
        self.wynagrodzenie.grid(row=1, column=2, padx=15, pady=5)
        self.dodajpracownika = ttk.Button(self.pracownicy, text="Dodaj pracownika", width=20)
        self.dodajpracownika.grid(row=0, rowspan=2, column=3, padx=15, pady=10)
        #Oplaty
        self.nazwaoplatylabel = ttk.Label(self.oplaty, text="Nazwa")
        self.nazwaoplatylabel.grid(row=0, column=0, padx=15)
        self.nazwaoplaty = ttk.Entry(self.oplaty)
        self.nazwaoplaty.grid(row=1, column=0, padx=15, pady=5)
        self.oplatalabel = ttk.Label(self.oplaty, text="Opłata jednorazowa")
        self.oplatalabel.grid(row=0, column=1, padx=15)
        self.oplata = ttk.Entry(self.oplaty)
        self.oplata.grid(row=1, column=1, padx=15, pady=5)
        self.oplatamiesiecznalabel = ttk.Label(self.oplaty, text="Opłata miesięczna")
        self.oplatamiesiecznalabel.grid(row=0, column=2, padx=15)
        self.oplatamiesieczna = ttk.Entry(self.oplaty, width=15)
        self.oplatamiesieczna.grid(row=1, column=2, padx=15, pady=5)
        self.dodajoplate = ttk.Button(self.oplaty, text="Dodaj opłate", width=20)
        self.dodajoplate.grid(row=0, rowspan=2, column=3, padx=15, pady=10)
        #------------------------------------------------------------------
        self.revas = ttk.LabelFrame(self, text="Revas", width=780, height=200)
        self.revas.grid(row=1, column=0, columnspan=2, padx=10)
        self.revas.grid_propagate(False)
        self.variable = tk.StringVar()
        self.variable.set("Oferty")
        self.oferta = ttk.OptionMenu(self.revas, self.variable)
        self.oferta.grid(row=0, column=0, padx=10, pady=10)

app = Application()
app.mainloop()